[build]
  command = "make build"
  functions = "functions"
  publish = "build"
[build.environment]
  # Change this path with the path to your repository
  GO_IMPORT_PATH = "github.com/tintack/netlify"